//
// Created by TUF_Fx507VV on 8/8/2025.
//

#ifndef GROUPCHATMANAGRE_GROUPCHATMANAGRE_H
#define GROUPCHATMANAGRE_GROUPCHATMANAGRE_H


class GroupChatManagre {

};


#endif //GROUPCHATMANAGRE_GROUPCHATMANAGRE_H
